name: 📦 Publish site

on:
 push:
   branches:
     - post

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: setup-node
              uses: actions/setup-node@v3
              with:
                node-version: 20
                cache: npm
                
            - id: files
              uses: jitterbit/get-changed-files@v1
            - id: publishable_posts
              name: Check for publishable posts
              run: |
                publishable_posts=""
                for changed_file in ${{ steps.files.outputs.added_modified }}; do
                  if [[ "${changed_file}" == "posts"* ]]; then
                    status=$(awk '/^Status:/ {print $2}' "${changed_file}")
                    if [[ "${status}" == "Published" ]]; then
                      publishable_posts="${publishable_posts} ${changed_file}"
                    fi
                  fi
                done
                echo "::set-output name=publishable_posts::${publishable_posts}"

            - if: steps.posts.outputs.publishable_posts
              name: Publish to medium
              uses: infraway/post-medium-action@v1.6.0
              with:
                access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
                markdown_file: ${{ steps.posts.outputs.publishable_posts }}
                base_url: https://medium.com/@shoto-morisaki