name: File check

on:
  pull_request:
    branches:
      - '*'

jobs:
  changed_files:
    runs-on: ubuntu-latest
    name: Test changed-files
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get all changed markdown files
        id: changed-markdown-files
        uses: tj-actions/changed-files@v44
        with:
          files: |
            **.md

      - name: List all changed markdown files
        if: steps.changed-markdown-files.outputs.any_changed == 'true'
        run: |
          echo "The following Markdown files were changed:"
          echo "${{ steps.changed-markdown-files.outputs.all_changed_files }}"
