name: 📦 Publish site

on:
  push: # pull_request | push
    branches-ignore: # branches | branches-ignore
      - main
      - development
    paths:
      - '**.md'

jobs:
  publish_blog_to_medium:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    name: Post to Medium (higgins.medium.com)
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install workflow dependencies
        run: npm install
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: posts
        name: Detecting posts from newly added files
        run: |
          i=0
          for added_file in ${{ steps.files.outputs.added }}; do
            echo "Do something with ${added_file}."
            if [[ "${added_file}" == "markdownTest.md"* ]];
            then
              echo "File ${added_file} matched post."
              echo "::set-output name=post${i}::${added_file}"
              echo "::set-output name=url${i}::https://portfolio-shoto.vercel.app/${added_file}"
              ((i=i+1))
            fi
          done

      - if: steps.posts.outputs.post0
        name: Medium Post
        uses: InfraWay/post-medium-action@v1.5.0
        with:
          access_token: ${{ secrets.MEDIUM_ACCESS_TOKEN }}
          markdown_file: ${{ steps.posts.outputs.post0 }}
          base_url: https://portfolio-shoto.vercel.app/